env:
  browser: false
  es6: true
extends:
  - prettier
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - prettier
  - '@typescript-eslint'
rules:
  'prettier/prettier': error
overrides:
  - files:
    - "src/**/*.js"
